### ISSUE TITLE
multiple-cert chain in “up” link from cert

### ISSUE THREAD

**Issue by FGasper** [ietf-wg-acme/acme#118]
The documentation seems unclear as to how certificate “up” links are to handle the case of multiple intermediate certificates between root and the issued certificate. Are both certificates part of the payload of the “up” link? Does each “up” link whose payload is not a root certificate (or “last-before-root”) have its own “up” link?

Thank you!

**Comment by bifurcation** [comment]
It seems pretty clear to me that the right answer is to have one "up" link per parent cert, but allow multiple links per cert.  We can add some text to clarify this.
