### ISSUE TITLE
MIME type for PEM-encoded (or anything non-DER) certificate??

### ISSUE THREAD

**Issue by FGasper** [ietf-wg-acme/acme#120]
The spec indicates that it’s possible to request certificates of types other than DER; however, there is no indication of what those MIME types are.

PEM would be a very useful format; would it be useful to indicate in here what that MIME type is, or at least where to find a list of MIME types that would work here?

**Comment by bifurcation** [comment]
The answer is `application/x-pem-file` :)  But I can agree that it would be good to remind people of this in the spec.

**Comment by XMB5** [comment]
CA certificates are `application/x-x509-ca-cert`
