### ISSUE TITLE
Hard-fail on unrecognized contact URI schemes

### ISSUE THREAD

**Issue by rolandshoemaker** [ietf-wg-acme/acme#159]
As far as I am aware there has been no explicit use case for this and Boulder explicitly disallows `tel:` URIs to be used.

`mailto` should be the only explicitly supported URI type in the spec and others should be left up to implementing CAs to document.

**Comment by jsha** [comment]
Conversation on-list went more in the direction of specifying that providing any contact with an unrecognized URI scheme should result in a hard error of `invalidContact`. Renaming appropriately.
