### ISSUE TITLE
http-01 protocol

### ISSUE THREAD

**Issue by billmasek** [ietf-wg-acme/acme#16]
1.  All of the Base64 strings are actually Base64 URL encoded
2.  In the Java support for big ints the top byte is set to 0 to eliminate issues with signs.  The thumbprint used here does not support that.  It would be useful to mention that in the spec.
3.  I think it would help if there was an appendix with a complete example from key to key authorization to help clarify the points above.

**Comment by kelunik** [comment]
Right, point 3 is pretty unclear and requires searching with your favorite search engine.
