### ISSUE TITLE
add a special token parameter in registration

### ISSUE THREAD

**Issue by startcomca** [ietf-wg-acme/acme#170]
StartCom plan to use ACME protocol for StartEncrypt, we need to identify the client's validation level, so the subscriber administration can generate a special token in the StartSSL.com account that send this token to the email address used in the registration.
At the registration, user need to enter email and this token with the certificate to let the CA system know this customer's validation level. 
After the CA system receive the email, the token and signing certificate, CA system know what type of certificate we can issue to this client; if this client account is class 4 validated, then the client can get EV SSL certificate, not DV SSL.
please add this a parameter to the ACME protocol, thanks.

**Comment by rolandshoemaker** [comment]
This request should be sent to the ACME mailing list (acme@ietf.org) for further discussion, it would also be very useful to know what your EV (or OV) validation flow would look like using ACME as most likely the current certificate application object would need to be changed to identify those requirements to the server.

**Comment by bifurcation** [comment]
This was fixed by #212
