### ISSUE TITLE
new-nonce endpoint should return 204 No Content

### ISSUE THREAD

**Issue by ashb** [ietf-wg-acme/acme#216]
The new-nonce endpoint added in #181 defines a new endpoint which returns information just in headers, but with a 200 response code.

I feel this would be more appropriate as a 204 No Content response code.

I'm not sure what the approach to making this sort of change is. Should I create this change as a PR?

**Comment by cpu** [comment]
@ashb A PR and a small note to the mailing list is probably the best approach.

I'm not an HTTP status lawyer but it seems like 204 is the more-appropriate choice in this context and [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.3.1) seems to agree with you:
>  Aside from responses to CONNECT, a 200 response always has a payload,
> though an origin server MAY generate a payload body of zero length.
> If no payload is desired, an origin server ought to send 204 (No
> Content) instead. 

I would :+1: the PR to change to 204 for `new-nonce` :-)
