### ISSUE TITLE
Source of configurable order object fields (trivial, editorial)

### ISSUE THREAD

**Issue by wiml** [ietf-wg-acme/acme#228]
The section on the "[Fields in Order Objects](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#fields-in-order-objects)" registry says that "Fields marked as "client configurable" may be included in a new-account request". This seems like a copy-paste-o, and perhaps should say that such fields may be included in a *new-order* request.

**Comment by cpu** [comment]
Good catch. I opened https://github.com/ietf-wg-acme/acme/pull/229 to fix.
