### ISSUE TITLE
Add domain.tld to <challenge1>.<challenge2>.<domain.tld>.acme.invalid

### ISSUE THREAD

**Issue by coolaj86** [ietf-wg-acme/acme#23]
Using common load-balance / proxy software it isn't possible to complete the challenge.

Here's the use case:

Proxy / Frontend Server (running haproxy in this case) is not handling TLS itself, but fronting connection.

The box behind it begins the challenge process.

The challenge comes in as `abc.xyz.acme.invalid`

There's no way to tell to which server the challenge was intended to go, it goes to the default server, which cannot complete the challenge.

If the challenge is changed to the format `abc.xyz.example.com.acme.invalid` the proxy could match explicitly against `*.example.com` and `*.example.com.acme.invalid` and forward the request to the correct machine.

**Comment by hlandau** [comment]
This might lead to issues with long domain names. The maximum length of a domain name is 255 bytes. It looks like domain names over about 110 bytes would therefore be a problem.

This could still be done, but the spec would need to state what should be done when an oversize domain name is specified; perhaps omitting the domain in that case. This would offer the utility of this addition to the majority of people doing validation.

**Comment by bifurcation** [comment]
This was discussed at the F2F at IETF 94, and there was pretty strong agreement that the benefits of having the domain name were not outweighed by the issues for long domain names.
