### ISSUE TITLE
ACME resources relations

### ISSUE THREAD

**Issue by andriymahats** [ietf-wg-acme/acme#236]
At the resource diagram in **6.1 Resources section**,
there is an **authz** resource related to **order** by “**up**” relation.

My question is for following case:

The client orders a certificate and
at the time of ordering it satisfied some authorizations (let’s say 2 of 3)
in previous transactions (possibly using pre-authorization: new-authz).

When client queries such previously satisfied authorization,
what order resource shall be pointed using “up” relation,
since that authorization can be used on many orders?

**Comment by bifurcation** [comment]
This has been addressed by removing the "up" link relation on authz resources (in #298).
