### ISSUE TITLE
ACME should expose an endpoint for CT SCT proofs

### ISSUE THREAD

**Issue by ekr** [ietf-wg-acme/acme#25]
The idea here is that if the CA opts not to log the precertificates it has a mechanism for publishing the proofs that are associated with a cert.

**Comment by jsha** [comment]
There are two good mechanisms to do this without adding a new endpoint:
 - The CA implementing ACME can include SCTs in its OCSP responses
 - Subscribers that wish to use SCTs, for instance in the TLS Extension mode of operation, may fetch those SCTs directly from the CT logs.

**Comment by ekr** [comment]
Neither of these seem like great substitutes. The first seems to violate straightforward reference semantics. The second puts a lot more work on the server.

**Comment by bifurcation** [comment]
I think this can be easily solved with a `Link: type=signed-certificate-timestamp`.
