### ISSUE TITLE
Delete and change ownership of acme repo

### ISSUE THREAD

**Issue by coolaj86** [ietf-wg-acme/acme#3]
There are a number of outstanding issues and activity on the official repository.

Rather than duplicating a new repository, it would serve the community well to have the ownership changed so that the ongoing discussion continues without any manual comment migration, double posting, and linking back and forth to hold a conversation.

See https://github.com/letsencrypt/acme-spec/issues/33#issuecomment-142342707

**Comment by richsalz** [comment]
The "official" respository?  You mean the LE one or this one?  The two might diverge.  There are also "note well" considerations for IP (non) issues.

**Comment by coolaj86** [comment]
Why would a standard diverge? Wouldn't that be.... not-a-standard?

Isn't the goal to *prevent* that sort of thing from happening?

https://xkcd.com/927/

**Comment by richsalz** [comment]
They will not all happen in lockstep.  LE has something deployed.  ACME has had one meeting.  IETF will probably have some changes and then LE will upgrade.  But even without that, we have the "note well" IP issue.
