### ISSUE TITLE
Allow contact information updates

### ISSUE THREAD

**Issue by kelunik** [ietf-wg-acme/acme#30]
Contact information may have been misspelled during registration. Contact information such as phone numbers may also change.

https://acme-staging.api.letsencrypt.org/directory exposes only the `new-reg` endpoint and that endpoint doesn't accept updates, because it has to respond with 409 Conflict for already existing keys.

There should be a way to update that information.

See also https://community.letsencrypt.org/t/clarify-the-email-flag-requirements/2603/8?u=kelunik.

**Comment by centminmod** [comment]
thanks @kelunik yes updating the contact email for registered LE account is a must have feature otherwise an LE notifications/renew notices may end up going to invalid email addresses.

**Comment by bifurcation** [comment]
Right now, the spec says that you can update anything in the registration with a `POST`:

```
If the client wishes to update this information in the future, it sends a POST
request with updated information to the registration URI. 
```

Note that the request goes to the *registration* URL, not the *new-registration* URL.  I'll add an example to the document to clarify.
