### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by JonHanna** [ietf-wg-acme/acme#313]
I'm not sure if this is the correct place for issues with the actual server, but https://acme-v01.api.letsencrypt.org/directory is returning me an error message of 

> An error occurred while processing your request.
> Reference #97.5df01202.1495189273.29f76a6f 

When accessed from several machines.

**Comment by richsalz** [comment]
No, this isn't the right place.  Contact LetsEncrypt directly.  This is for discussing the IETF protocol.
