### ISSUE TITLE
Any chance the 'E' in ACME could stand for "Exchange"

### ISSUE THREAD

**Issue by ebekker** [ietf-wg-acme/acme#32]
I've been curious what the *Environment* in "Automatic Certificate Management Environment" meant since the LE project first kicked off, and while I can come up with a few ideas, I wonder if it makes more sense to have the acronym stand for Automated Certificate Management and Exchange?

I'm sure I'm not the first one to suggest this, but I didn't see it in any of the comments or tickets, and I just wanted to throw it out there before the spec is finalized and ratified by the IETF.

**Comment by coolaj86** [comment]
Or change the name entirely.

When I think of ACME I think of Wile E Coyote, Time Bombs, and Anvils, Tornado seeds, etc.
And so do [les googles](https://www.google.com/search?q=acme&es_sm=91&source=lnms&tbm=isch&sa=X&ved=0CAkQ_AUoA2oVChMIy9iapZSFyQIVFEhjCh2q9g8y&biw=1384&bih=990). 

Maybe "Automatic Registration for Authentic Domain Name Certificates" and call it CertReg for short... or go crazy and somehow rearrange it to spell ARACNID - to immortalize the glory of the web.

**Comment by bmintz** [comment]
ARACNID gives new meaning to World-Wide _Web_. :stuck_out_tongue_winking_eye:
