### ISSUE TITLE
OOB-01 should take an empty object payload

### ISSUE THREAD

**Issue by jsha** [ietf-wg-acme/acme#328]
The other challenges don't expect you to post a payload containing a type field, so it's inconsistent for OOB-01 to do so. It should just take an empty object "{}" as its payload.

**Comment by bifurcation** [comment]
This seems fine.  It seems to be protected from replay by the `nonce` and `url` parameters.  I think we're OK leaving the challenge name at "oob-01", since this isn't a breaking change.
