### ISSUE TITLE
Keychain deploy

### ISSUE THREAD

**Issue by jsrcomp** [ietf-wg-acme/acme#338]
MacOS needs root privileges to import into System keychain.  Can you setup the keychain.sh to use sudo?

**Comment by richsalz** [comment]
i think you posted this issue to the wrong repo.

**Comment by jsrcomp** [comment]
My apologies

On Aug 18, 2017, at 20:25, Rich Salz <notifications@github.com<mailto:notifications@github.com>> wrote:


i think you posted this issue to the wrong repo.
