### ISSUE TITLE
pre-authorization clean up

### ISSUE THREAD

**Issue by andriymahats** [ietf-wg-acme/acme#364]
Hi

in the section on pre-authz there is this sentence:

To request authorization for an identifier, the client sends a POST request to the new-authorization resource specifying the identifier for which authorization is being requested and how the server should behave with respect to existing authorizations for this identifier.

the part "and how the server should behave with respect to existing authorizations for this identifier" probably is obsoleted

**Comment by cpu** [comment]
Hi @andriymahats,

I submitted https://github.com/ietf-wg-acme/acme/pull/365 to fix this. Thanks for spotting & reporting :-)
