### ISSUE TITLE
xml2rfc broken

### ISSUE THREAD

**Issue by Torxed** [ietf-wg-acme/acme#372]
xml2rfc -q draft-ietf-acme-acme.xml -o draft-ietf-acme-acme.txt --text
    ERROR: Unable to parse the XML document: draft-ietf-acme-acme.xml
     <string>: Line 2: Extra content at the end of the document
     <string>: Line 2: Extra content at the end of the document
    make: *** [lib/main.mk:83: draft-ietf-acme-acme.txt] Error 1
    rm draft-ietf-acme-acme.xml

(pulled from github, `pip install xml2rfc` was used to install the damn thing)

**Comment by sophie-h** [comment]
Sounds like kramdown-rfc2629 is producing an invalid XML document. I am using v1.0.36 packaged with debian stretch.

**Comment by Torxed** [comment]
I mainly always run at least something released within half a year or at least a year.
So the versions I'm using are:
 * xml2rfc - v2.8.2
 * kramdown-rfc2629 - v1.16.2

This is by no means an offence to you running debian, but maybe using this sort of tool to create something isn't really a good way to go if it breaks this hard in between versions? Is there a simpler solution than first creating a XML, and then trying to port it?

**Comment by sophie-h** [comment]
Maybe it helps if you have a look at the versions [used by the build server](https://circleci.com/gh/ietf-wg-acme/acme/975#tests/containers/0)

```
Fetching: kramdown-1.14.0.gem (100%)
Successfully installed kramdown-1.14.0
…
Fetching: kramdown-rfc2629-1.2.7.gem (100%)
Successfully installed kramdown-rfc2629-1.2.7
```

**Comment by Torxed** [comment]
I followed the build instructions, nothing more, nothing less.

    sudo pip install xml2rfc
    gem install kramdown-rfc2629
    make

Not sure why I would want to downgrade to an older version?
If that's the case, then close this and I'll eject from this project.

**Comment by jsha** [comment]
> Is there a simpler solution than first creating a XML, and then trying to port it?

This is a fairly standard approach used by a variety of RFCs.

Perhaps it would help if you described the problem you are trying to solve? Most edits can be done without needing to necessarily install the xml2rfc tool.

**Comment by bifurcation** [comment]
All the PRs are building in CI, so I'm closing this WORKSFORME.
