### ISSUE TITLE
"xn--" (two dashes) is converted to "xn–" (EN DASH, unicode U+2013)

### ISSUE THREAD

**Issue by joernheissler** [ietf-wg-acme/acme#378]
In https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.7.1.4:
```
prefix “xn–” as defined
```
This should be:
```
prefix “xn--” as defined
```

**Comment by cpu** [comment]
Opened https://github.com/ietf-wg-acme/acme/pull/380 with a fix. Thanks!
