### ISSUE TITLE
Wording in Introduction

### ISSUE THREAD

**Issue by joernheissler** [ietf-wg-acme/acme#404]
> For example, the external
account binding feature (see {{external-account-binding}}) can be used to
associate authorizations with an account that were not validated through the
ACME authorization process.

To me (non-native English speaker) "were not" refers to "an account" which would be a grammar mistake. If it refers to "authorizations" would it be better to switch "authorizations" and "an account"?

**Comment by bifurcation** [comment]
I think it is technically correct (it does refer to "authorizations"), but I agree it's an awkward sentence.  Filed #409 to address.
