### ISSUE TITLE
Good reference for Access-Control-Allow-Origin?

### ISSUE THREAD

**Issue by seanturner** [ietf-wg-acme/acme#434]
We need a normative reference for Access-Control-Allow-Origin.  https://www.iana.org/assignments/message-headers/message-headers.xhtml lists Access-Control-Allow-Origin as provisional.

**Comment by bifurcation** [comment]
The right reference is CORS:

https://www.w3.org/TR/cors/

@mnot or @martinthomson might know how best to reference it.

**Comment by seanturner** [comment]
Should we get the IANA registry changed to permanent from provisional?

spt
