### ISSUE TITLE
error for failed revocation request?

### ISSUE THREAD

**Issue by seanturner** [ietf-wg-acme/acme#436]
In s7.6, it seems like we should indicate what error is returned:

   If the revocation fails, the server returns an error.

The draft this nicely in many others places in the draft.

**Comment by bifurcation** [comment]
This is a good idea, sorry for missing it earlier.

@felixfontein - Do you have any thoughts on other cases besides "already revoked" that would (a) not require user interaction and (b) not be covered by other current error codes?  

@seanturner - Would you mind making a PR to add an `alreadyRevoked` error code (and anything else that @felixfontein comes up with), and note it in the revocation section?

**Comment by cpu** [comment]
> @felixfontein - Do you have any thoughts on other cases besides "already revoked" that would (a) not require user interaction and (b) not be covered by other current error codes?

I thought of one to consider in [my review of #438](https://github.com/ietf-wg-acme/acme/pull/438#pullrequestreview-144922626): 
> Should we also specify the error type for a request indicating revocation of a certificate that the CA does not know? HTTP Status Code 400 with a new certificateDoesNotExist error type?

**Comment by cpu** [comment]
> HTTP Status Code 400 with a new certificateDoesNotExist error type?

It looks like Boulder uses 404 and a generic malformed problem type for this case:
https://github.com/letsencrypt/boulder/blob/0cb28c9e0281fdae47431b68d073c7336b7759b2/wfe2/wfe.go#L616
https://github.com/letsencrypt/boulder/blob/0cb28c9e0281fdae47431b68d073c7336b7759b2/probs/probs.go#L126

**Comment by felixfontein** [comment]
@bifurcation So far I couldn't think of anything else. I'm totally happy with #438 :-)

**Comment by bifurcation** [comment]
Fixed by #438
