### ISSUE TITLE
Automatically build the spec and publish as `gh-pages`

### ISSUE THREAD

**Issue by nbraud** [ietf-wg-acme/acme#45]
Hi,

It would be highly helpful for to have an up-to-date rendering of branch `master` available as <https://ietf-wg-acme.github.io/acme>, especially since it is linked from README.md.

Since the Makefile template used has [support for pushing to gh-pages](https://github.com/martinthomson/i-d-template/blob/master/ghpages.mk), it should be enough (for instance) to:

1. generate a GitHub token with privilege to push to this specific repo;
2. encrypt `GH_TOKEN=<the actual token>` [to travis' public key](http://docs.travis-ci.com/user/encryption-keys/);
3. include the encrypted blob in [`.travis.yml`](https://github.com/ietf-wg-acme/acme/blob/master/.travis.yml), under `env.secure`;
4. sign this repository up with Travis CI for automated builds.

_NOTE:_ This technically give Travis CI the ability to push to this repository, should they be dishonest.
_NOTE:_ Using Travis CI is not a requirement, but it would probably be the easiest to setup.

**Comment by bifurcation** [comment]
@martinthomson Can you advise on this?

**Comment by martinthomson** [comment]
Anyone with admin access to the repo can enable this using travis or circle.  However, when I suggested this to @richsalz, he was reluctant to do so.  I don't agree with his reasons, so you should ask him why.

Note that both services offer a web configuration interface.  You should be able to put the environment variable there.

I will open a PR for the latest template, which is much nicer to look at.

**Comment by richsalz** [comment]
Remind me what I said, maybe I was wrong.

**Comment by martinthomson** [comment]
@richsalz, https://github.com/ietf-wg-acme/acme/pull/19#issuecomment-149964204

I've found that an up-to-date editor's copy is invaluable when it comes to getting new contributions.  Sometimes, it even avoids situations where an issue is raised multiple times by casual contributors.

**Comment by richsalz** [comment]
Okay, I was wrong.  Looks like @bifurcation set it all up and we can close this?

**Comment by ebekker** [comment]
This is great, thanks all!  Would it be possible to tag the doc with a timestamp to be sure when it was generated?  Or perhaps have a separate page that shows the last generated time (perhaps with other related meta data)?  This would be similar to the LE [staging](https://acme-staging.api.letsencrypt.org/build) and [beta](https://acme-v01.api.letsencrypt.org/build) latest build statuses.

**Comment by richsalz** [comment]
The date's not enough?

**Comment by ebekker** [comment]
I'm sorry, did I miss it?  I was looking at [this](http://ietf-wg-acme.github.io/acme/) copy and I only found two dates, the expiration date and I guess the manually-managed update date in the upper right corner below the contributors.  Is there another generated date in the doc already?

**Comment by ebekker** [comment]
Actually, I guess if the project page for the CI build (i.e. in something like Travis or CircleCI) is documented, that would give you all the same info, and more.

**Comment by richsalz** [comment]
Added a "build history" link to the README.md, so we can now close this issue.
