### ISSUE TITLE
Clarify how to handle bad new-certificate requests

### ISSUE THREAD

**Issue by richsalz** [ietf-wg-acme/acme#47]
We need to clarify when an ACME server can ignore attributes in a request that it doesn't like, and when it should ignore them and proceed.  For example, if a requested validity date is longer than the policy, should it error back or just ignore that attribute and issue a cert good for as long as it wants?  That seems okay.  But what about an unsupported request  for issuance in the future?  Ignoring that seems wrong, and risky.

**Comment by jsha** [comment]
I think in general ACME should take the approach of refusing to issue a cert if requested parameters (dates, or extensions) are unacceptable. It's cheap for the client to re-request with acceptable parameters, assuming the error message is detailed enough.

**Comment by bifurcation** [comment]
Scoping this down to new-certificate requests, since there's not really enough latitude in the other types of request to cause this problem.

**Comment by hardie** [comment]
Agreed in B.A. to fail, fail, fail, but return information helpful to a human, explicitly not machine-recoverable.  It may be possible to give a trivial amount of altitude (e.g. 90 days--will it not be okay if 90-days minus 15 seconds is given?)
