### ISSUE TITLE
Clarify whether base64 encoding without padding applies to key authorization strings

### ISSUE THREAD

**Issue by janeczku** [ietf-wg-acme/acme#64]
The current draft stipulates Base64 encoding without padding in relation to JSON data. It is unclear whether omitting the padding characters also applies to the Base64url encoding of key authorization resources (which are not JSON objects).

[Terminology](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#terminology)
> "Since JSON is a text-based format, binary fields are Base64-encoded. For Base64 encoding, we use the variant defined in {{RFC7515}}. The important features of this encoding are (1) that it uses the URL-safe character set, and (2) that "=" padding characters are stripped."

[DNS challenge](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#dns)
>  "The record provisioned to the DNS is the base64url encoding of this digest."

To avoid ambiguity with regards to the encoding of the key authorization string (with padding / without padding) either specify "Base64url Encoding" in the terminology section or change the wording of the aforementioned provision so it is clear that the RFC7515 variant applies to any Base64 encoding throughout the spec.

Reference: https://github.com/letsencrypt/boulder/pull/1295

**Comment by jmhodges** [comment]
Data for the discussion: boulder uses Base64url without padding (a.k.a. [base64.RawURLEncoding](https://golang.org/pkg/encoding/base64/#RawURLEncoding)) everywhere.

(The DNS challenge deployed to boulder's staging instance was buggy, has been fixed in master, and is going to be deployed to again Real Soon Now)
